
MACOS_VER = 10.9

cflags += -stdlib=libc++ -mmacosx-version-min=$(MACOS_VER)

# library name
lib.name = helloworld

# input source file (class name == source file basename)
class.sources = helloworld.cpp

# all extra files to be included in binary distribution of the library
datafiles =

# include Makefile.pdlibbuilder from submodule directory 'pd-lib-builder'
include ../Makefile.pdlibbuilder


